DROP DATABASE IF EXISTS notes_app;

CREATE DATABASE notes_app
  CHARACTER SET utf8mb4
  COLLATE utf8mb4_unicode_ci;

USE notes_app;

CREATE TABLE users (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(50) NOT NULL UNIQUE,
    email VARCHAR(255) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE notes (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    user_id INT UNSIGNED NOT NULL,
    folder_id INT UNSIGNED NULL,
    title VARCHAR(255) NOT NULL,
    content TEXT NOT NULL,
    FOREIGN KEY (user_id) REFERENCES users(id)
      ON DELETE CASCADE,
    FOREIGN KEY (folder_id) REFERENCES folders(id)
      ON DELETE SET NULL
);

CREATE TABLE kanban (
    note_id INT NOT NULL,
    uncategorized BOOLEAN DEFAULT TRUE,
    todo BOOLEAN DEFAULT FALSE,
    doing BOOLEAN DEFAULT FALSE,
    done BOOLEAN DEFAULT FALSE,
    FOREIGN KEY (note_id) REFERENCES notes(id)
);
